name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Frontend
      - name: Build & Push Front
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          # CAMBIA 'tu_usuario' POR EL TUYO
          tags: ${{ secrets.DOCKER_USERNAME }}/proyecto-front:latest

      # Build Backend
      - name: Build & Push Back
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          # CAMBIA 'tu_usuario' POR EL TUYO
          tags: ${{ secrets.DOCKER_USERNAME }}/proyecto-back:latest

  deploy-aws:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Refrescar ASG
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name app-asg-produccion \
            --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 300}'